# Generated by Django 4.1.4 on 2022-12-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookexapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
