# Generated by Django 4.1.3 on 2023-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookexapp', '0002_delete_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUsersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
