# Generated by Django 4.1.3 on 2023-03-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookexapp', '0004_remove_newsletteruserslist_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellerBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
