# Generated by Django 4.1.3 on 2023-03-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookexapp', '0005_bestsellerbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellerbooks',
            name='img',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
